In [5]:
import os
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, ConcatDataset
from PIL import Image
import torch
import timm
from transformers import BeitForImageClassification, DeiTForImageClassification, Swinv2ForImageClassification, ConvNextForImageClassification, ConvNextV2ForImageClassification, Dinov2ForImageClassification
from torch.optim import Adamax, RMSprop, SGD
from torch.optim.lr_scheduler import StepLR
from tqdm import tqdm 
import time
import timm
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


In [6]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

data_dir = os.path.join('datasets', 'Boya3')
print(data_dir)

fold_dirs = [fold for fold in os.listdir(data_dir) if os.path.isdir(os.path.join(data_dir, fold)) and "fold" in fold]
fold_results = {}
print(fold_dirs)

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
print(os.environ["PYTORCH_CUDA_ALLOC_CONF"])

datasets/Boya3
['fold3', 'fold1', 'fold4', 'fold5', 'fold2']
expandable_segments:True


In [7]:
def train_model(fold_idx):
    model = Dinov2ForImageClassification.from_pretrained(
        "facebook/dinov2-small",
        num_labels=18,
        ignore_mismatched_sizes=True
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    print(device)
    print(model)

    train_path = os.path.join(data_dir, f"fold{fold_idx}", 'train')
    test_path = os.path.join(data_dir, f"fold{fold_idx}", 'test')
    
    train_dataset = datasets.ImageFolder(root=train_path, transform=transform)
    val_dataset = datasets.ImageFolder(root=test_path, transform=transform)

    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

    optimizer = RMSprop(model.parameters(), lr=1e-5, momentum=0.9, weight_decay=5e-4)
    scheduler = StepLR(optimizer, step_size=5, gamma=0.1)
    
    best_loss = float('inf')
    best_model_path = os.path.join(data_dir, f"best_model_fold{fold_idx}.pth")

    for epoch in range(20):
        model.train()
        total_loss = 0

        with tqdm(train_loader, desc=f"Fold {fold_idx} Epoch {epoch + 1}/20", unit="batch") as t:
            for batch in t:
                inputs, labels = batch[0].to(device), batch[1].to(device)
                outputs = model(inputs, labels=labels)
                loss = outputs.loss

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                total_loss += loss.item()
                t.set_postfix(loss=loss.item())

                del inputs, labels, outputs, loss
                torch.cuda.empty_cache()

        avg_loss = total_loss / len(train_loader)
        print(f"Fold {fold_idx} Epoch {epoch + 1}/20, Loss: {avg_loss}")

        scheduler.step()

        if avg_loss < best_loss:
            best_loss = avg_loss
            torch.save(model.state_dict(), best_model_path)
            print(f"New best model saved with loss: {best_loss}")



def evaluate_model(fold_idx):
    
    model_path = os.path.join(data_dir, f"best_model_fold{fold_idx}.pth")
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    model = Dinov2ForImageClassification.from_pretrained(
        "facebook/dinov2-small",
        num_labels=18,
        ignore_mismatched_sizes=True
    )

    model.load_state_dict(torch.load(model_path))
    model = model.to(device)
    model.eval()

    test_path = os.path.join(data_dir, f"fold{fold_idx}", 'test')
    val_dataset = datasets.ImageFolder(root=test_path, transform=transform)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

    val_targets = []
    val_predictions = []

    with torch.no_grad():
        for inputs, targets in val_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            predictions = torch.argmax(outputs.logits, dim=1)
            val_targets.extend(targets.cpu().numpy())
            val_predictions.extend(predictions.cpu().numpy())

    cm = confusion_matrix(val_targets, val_predictions)
    print(f"Fold {fold_idx} Confusion Matrix:")
    print(cm)
    with open(os.path.join(data_dir, f'cm_{fold_idx}.txt'), 'w') as f:
        print(cm, file=f)

    report = classification_report(val_targets, val_predictions, output_dict=True, target_names=val_dataset.classes)
    print(report)
    with open(os.path.join(data_dir, f'report_{fold_idx}.txt'), 'w') as f:
        print(report, file=f)

    fold_results[fold_idx] = (report, cm)

In [8]:
for i in range(1, 6):
    train_model(i)
    
for i in range(1,6):
    evaluate_model(i)

Some weights of Dinov2ForImageClassification were not initialized from the model checkpoint at facebook/dinov2-small and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


cuda
Dinov2ForImageClassification(
  (dinov2): Dinov2Model(
    (embeddings): Dinov2Embeddings(
      (patch_embeddings): Dinov2PatchEmbeddings(
        (projection): Conv2d(3, 384, kernel_size=(14, 14), stride=(14, 14))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): Dinov2Encoder(
      (layer): ModuleList(
        (0-11): 12 x Dinov2Layer(
          (norm1): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
          (attention): Dinov2SdpaAttention(
            (attention): Dinov2SdpaSelfAttention(
              (query): Linear(in_features=384, out_features=384, bias=True)
              (key): Linear(in_features=384, out_features=384, bias=True)
              (value): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): Dinov2SelfOutput(
              (dense): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=F

Fold 1 Epoch 1/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.76]


Fold 1 Epoch 1/20, Loss: 2.302917218283762
New best model saved with loss: 2.302917218283762


Fold 1 Epoch 2/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=2.23]


Fold 1 Epoch 2/20, Loss: 2.041958336211458
New best model saved with loss: 2.041958336211458


Fold 1 Epoch 3/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=2.08]


Fold 1 Epoch 3/20, Loss: 1.9857762346539316
New best model saved with loss: 1.9857762346539316


Fold 1 Epoch 4/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.87]


Fold 1 Epoch 4/20, Loss: 1.961775606191611
New best model saved with loss: 1.961775606191611


Fold 1 Epoch 5/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.7] 


Fold 1 Epoch 5/20, Loss: 1.9309610724449158
New best model saved with loss: 1.9309610724449158


Fold 1 Epoch 6/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=2.08]


Fold 1 Epoch 6/20, Loss: 1.8415130350408675
New best model saved with loss: 1.8415130350408675


Fold 1 Epoch 7/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.4] 


Fold 1 Epoch 7/20, Loss: 1.8228256864638268
New best model saved with loss: 1.8228256864638268


Fold 1 Epoch 8/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=2.01]


Fold 1 Epoch 8/20, Loss: 1.8090212303626387
New best model saved with loss: 1.8090212303626387


Fold 1 Epoch 9/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.68]


Fold 1 Epoch 9/20, Loss: 1.7971442390846302
New best model saved with loss: 1.7971442390846302


Fold 1 Epoch 10/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.8] 


Fold 1 Epoch 10/20, Loss: 1.7884480768366704
New best model saved with loss: 1.7884480768366704


Fold 1 Epoch 11/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.85]


Fold 1 Epoch 11/20, Loss: 1.7706793739071376
New best model saved with loss: 1.7706793739071376


Fold 1 Epoch 12/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.65]


Fold 1 Epoch 12/20, Loss: 1.7672905110860173
New best model saved with loss: 1.7672905110860173


Fold 1 Epoch 13/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.96]


Fold 1 Epoch 13/20, Loss: 1.7652120707155783
New best model saved with loss: 1.7652120707155783


Fold 1 Epoch 14/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.64]


Fold 1 Epoch 14/20, Loss: 1.7640990211239345
New best model saved with loss: 1.7640990211239345


Fold 1 Epoch 15/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.68]


Fold 1 Epoch 15/20, Loss: 1.7629521202437486
New best model saved with loss: 1.7629521202437486


Fold 1 Epoch 16/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.58]


Fold 1 Epoch 16/20, Loss: 1.7606240488305878
New best model saved with loss: 1.7606240488305878


Fold 1 Epoch 17/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=2.12]


Fold 1 Epoch 17/20, Loss: 1.760447375382049
New best model saved with loss: 1.760447375382049


Fold 1 Epoch 18/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.69]


Fold 1 Epoch 18/20, Loss: 1.7601240658307378
New best model saved with loss: 1.7601240658307378


Fold 1 Epoch 19/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.84]


Fold 1 Epoch 19/20, Loss: 1.7600274798990805
New best model saved with loss: 1.7600274798990805


Fold 1 Epoch 20/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.8] 


Fold 1 Epoch 20/20, Loss: 1.7599287323559387
New best model saved with loss: 1.7599287323559387


Some weights of Dinov2ForImageClassification were not initialized from the model checkpoint at facebook/dinov2-small and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


cuda
Dinov2ForImageClassification(
  (dinov2): Dinov2Model(
    (embeddings): Dinov2Embeddings(
      (patch_embeddings): Dinov2PatchEmbeddings(
        (projection): Conv2d(3, 384, kernel_size=(14, 14), stride=(14, 14))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): Dinov2Encoder(
      (layer): ModuleList(
        (0-11): 12 x Dinov2Layer(
          (norm1): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
          (attention): Dinov2SdpaAttention(
            (attention): Dinov2SdpaSelfAttention(
              (query): Linear(in_features=384, out_features=384, bias=True)
              (key): Linear(in_features=384, out_features=384, bias=True)
              (value): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): Dinov2SelfOutput(
              (dense): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=F

Fold 2 Epoch 1/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.95]


Fold 2 Epoch 1/20, Loss: 2.3094877038575428
New best model saved with loss: 2.3094877038575428


Fold 2 Epoch 2/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.6] 


Fold 2 Epoch 2/20, Loss: 2.0213671130470083
New best model saved with loss: 2.0213671130470083


Fold 2 Epoch 3/20: 100%|██████████| 316/316 [02:06<00:00,  2.51batch/s, loss=1.66]


Fold 2 Epoch 3/20, Loss: 1.967638657440113
New best model saved with loss: 1.967638657440113


Fold 2 Epoch 4/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.47]


Fold 2 Epoch 4/20, Loss: 1.933754666696621
New best model saved with loss: 1.933754666696621


Fold 2 Epoch 5/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=2.11]


Fold 2 Epoch 5/20, Loss: 1.9108852940269663
New best model saved with loss: 1.9108852940269663


Fold 2 Epoch 6/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.56]


Fold 2 Epoch 6/20, Loss: 1.8131376859507984
New best model saved with loss: 1.8131376859507984


Fold 2 Epoch 7/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.52]


Fold 2 Epoch 7/20, Loss: 1.785043244120441
New best model saved with loss: 1.785043244120441


Fold 2 Epoch 8/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.89]


Fold 2 Epoch 8/20, Loss: 1.7727252542972565
New best model saved with loss: 1.7727252542972565


Fold 2 Epoch 9/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.97]


Fold 2 Epoch 9/20, Loss: 1.763038082590586
New best model saved with loss: 1.763038082590586


Fold 2 Epoch 10/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.47]


Fold 2 Epoch 10/20, Loss: 1.7527060693577876
New best model saved with loss: 1.7527060693577876


Fold 2 Epoch 11/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.62]


Fold 2 Epoch 11/20, Loss: 1.7294171863718877
New best model saved with loss: 1.7294171863718877


Fold 2 Epoch 12/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.83]


Fold 2 Epoch 12/20, Loss: 1.7249449087849147
New best model saved with loss: 1.7249449087849147


Fold 2 Epoch 13/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.15]


Fold 2 Epoch 13/20, Loss: 1.722710336310954
New best model saved with loss: 1.722710336310954


Fold 2 Epoch 14/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.72]


Fold 2 Epoch 14/20, Loss: 1.7211649730990204
New best model saved with loss: 1.7211649730990204


Fold 2 Epoch 15/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.88]


Fold 2 Epoch 15/20, Loss: 1.7204428545281858
New best model saved with loss: 1.7204428545281858


Fold 2 Epoch 16/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.89]


Fold 2 Epoch 16/20, Loss: 1.7167072646980044
New best model saved with loss: 1.7167072646980044


Fold 2 Epoch 17/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.6] 


Fold 2 Epoch 17/20, Loss: 1.7158356467379798
New best model saved with loss: 1.7158356467379798


Fold 2 Epoch 18/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.28]


Fold 2 Epoch 18/20, Loss: 1.7151032829586463
New best model saved with loss: 1.7151032829586463


Fold 2 Epoch 19/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.76]


Fold 2 Epoch 19/20, Loss: 1.7157141287115556


Fold 2 Epoch 20/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.56]


Fold 2 Epoch 20/20, Loss: 1.7152266626871084


Some weights of Dinov2ForImageClassification were not initialized from the model checkpoint at facebook/dinov2-small and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


cuda
Dinov2ForImageClassification(
  (dinov2): Dinov2Model(
    (embeddings): Dinov2Embeddings(
      (patch_embeddings): Dinov2PatchEmbeddings(
        (projection): Conv2d(3, 384, kernel_size=(14, 14), stride=(14, 14))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): Dinov2Encoder(
      (layer): ModuleList(
        (0-11): 12 x Dinov2Layer(
          (norm1): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
          (attention): Dinov2SdpaAttention(
            (attention): Dinov2SdpaSelfAttention(
              (query): Linear(in_features=384, out_features=384, bias=True)
              (key): Linear(in_features=384, out_features=384, bias=True)
              (value): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): Dinov2SelfOutput(
              (dense): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=F

Fold 3 Epoch 1/20: 100%|██████████| 316/316 [02:08<00:00,  2.47batch/s, loss=1.7] 


Fold 3 Epoch 1/20, Loss: 2.220404303149332
New best model saved with loss: 2.220404303149332


Fold 3 Epoch 2/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=2.36]


Fold 3 Epoch 2/20, Loss: 2.0045212699642665
New best model saved with loss: 2.0045212699642665


Fold 3 Epoch 3/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.76]


Fold 3 Epoch 3/20, Loss: 1.9695331401462797
New best model saved with loss: 1.9695331401462797


Fold 3 Epoch 4/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=2.08]


Fold 3 Epoch 4/20, Loss: 1.9229548924331423
New best model saved with loss: 1.9229548924331423


Fold 3 Epoch 5/20: 100%|██████████| 316/316 [02:07<00:00,  2.47batch/s, loss=1.88]


Fold 3 Epoch 5/20, Loss: 1.8895020496241655
New best model saved with loss: 1.8895020496241655


Fold 3 Epoch 6/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=2.08]


Fold 3 Epoch 6/20, Loss: 1.8020342746867408
New best model saved with loss: 1.8020342746867408


Fold 3 Epoch 7/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.62]


Fold 3 Epoch 7/20, Loss: 1.7784709047667588
New best model saved with loss: 1.7784709047667588


Fold 3 Epoch 8/20: 100%|██████████| 316/316 [02:06<00:00,  2.51batch/s, loss=1.99]


Fold 3 Epoch 8/20, Loss: 1.7671818714353102
New best model saved with loss: 1.7671818714353102


Fold 3 Epoch 9/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.47]


Fold 3 Epoch 9/20, Loss: 1.7606347640858422
New best model saved with loss: 1.7606347640858422


Fold 3 Epoch 10/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.96]


Fold 3 Epoch 10/20, Loss: 1.7501696778249136
New best model saved with loss: 1.7501696778249136


Fold 3 Epoch 11/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.78]


Fold 3 Epoch 11/20, Loss: 1.728519633223739
New best model saved with loss: 1.728519633223739


Fold 3 Epoch 12/20: 100%|██████████| 316/316 [02:07<00:00,  2.47batch/s, loss=2.05]


Fold 3 Epoch 12/20, Loss: 1.7252451966080484
New best model saved with loss: 1.7252451966080484


Fold 3 Epoch 13/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=2.04]


Fold 3 Epoch 13/20, Loss: 1.723184877181355
New best model saved with loss: 1.723184877181355


Fold 3 Epoch 14/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.9] 


Fold 3 Epoch 14/20, Loss: 1.7216083328180676
New best model saved with loss: 1.7216083328180676


Fold 3 Epoch 15/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.7] 


Fold 3 Epoch 15/20, Loss: 1.7200413972516604
New best model saved with loss: 1.7200413972516604


Fold 3 Epoch 16/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.58]


Fold 3 Epoch 16/20, Loss: 1.716577246219297
New best model saved with loss: 1.716577246219297


Fold 3 Epoch 17/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.94]


Fold 3 Epoch 17/20, Loss: 1.716556528701058
New best model saved with loss: 1.716556528701058


Fold 3 Epoch 18/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.58]


Fold 3 Epoch 18/20, Loss: 1.7158358779889118
New best model saved with loss: 1.7158358779889118


Fold 3 Epoch 19/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.71]


Fold 3 Epoch 19/20, Loss: 1.7158149394053448
New best model saved with loss: 1.7158149394053448


Fold 3 Epoch 20/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.8] 


Fold 3 Epoch 20/20, Loss: 1.7157087480720086
New best model saved with loss: 1.7157087480720086


Some weights of Dinov2ForImageClassification were not initialized from the model checkpoint at facebook/dinov2-small and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


cuda
Dinov2ForImageClassification(
  (dinov2): Dinov2Model(
    (embeddings): Dinov2Embeddings(
      (patch_embeddings): Dinov2PatchEmbeddings(
        (projection): Conv2d(3, 384, kernel_size=(14, 14), stride=(14, 14))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): Dinov2Encoder(
      (layer): ModuleList(
        (0-11): 12 x Dinov2Layer(
          (norm1): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
          (attention): Dinov2SdpaAttention(
            (attention): Dinov2SdpaSelfAttention(
              (query): Linear(in_features=384, out_features=384, bias=True)
              (key): Linear(in_features=384, out_features=384, bias=True)
              (value): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): Dinov2SelfOutput(
              (dense): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=F

Fold 4 Epoch 1/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.97]


Fold 4 Epoch 1/20, Loss: 2.3414016875285135
New best model saved with loss: 2.3414016875285135


Fold 4 Epoch 2/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.87]


Fold 4 Epoch 2/20, Loss: 2.028745460359356
New best model saved with loss: 2.028745460359356


Fold 4 Epoch 3/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=2.09]


Fold 4 Epoch 3/20, Loss: 1.9688701271256315
New best model saved with loss: 1.9688701271256315


Fold 4 Epoch 4/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.9] 


Fold 4 Epoch 4/20, Loss: 1.9464160283155079
New best model saved with loss: 1.9464160283155079


Fold 4 Epoch 5/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.83]


Fold 4 Epoch 5/20, Loss: 1.9136802893650682
New best model saved with loss: 1.9136802893650682


Fold 4 Epoch 6/20: 100%|██████████| 316/316 [02:07<00:00,  2.48batch/s, loss=1.73]


Fold 4 Epoch 6/20, Loss: 1.8080561153496368
New best model saved with loss: 1.8080561153496368


Fold 4 Epoch 7/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.7] 


Fold 4 Epoch 7/20, Loss: 1.7847934546349924
New best model saved with loss: 1.7847934546349924


Fold 4 Epoch 8/20: 100%|██████████| 316/316 [02:06<00:00,  2.49batch/s, loss=1.61]


Fold 4 Epoch 8/20, Loss: 1.77298237741748
New best model saved with loss: 1.77298237741748


Fold 4 Epoch 9/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.83]


Fold 4 Epoch 9/20, Loss: 1.7601166552380672
New best model saved with loss: 1.7601166552380672


Fold 4 Epoch 10/20: 100%|██████████| 316/316 [02:07<00:00,  2.49batch/s, loss=1.69]


Fold 4 Epoch 10/20, Loss: 1.7507553689087494
New best model saved with loss: 1.7507553689087494


Fold 4 Epoch 11/20: 100%|██████████| 316/316 [02:04<00:00,  2.53batch/s, loss=1.97]


Fold 4 Epoch 11/20, Loss: 1.7306994995738887
New best model saved with loss: 1.7306994995738887


Fold 4 Epoch 12/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=2.03]


Fold 4 Epoch 12/20, Loss: 1.7273690794842154
New best model saved with loss: 1.7273690794842154


Fold 4 Epoch 13/20: 100%|██████████| 316/316 [02:06<00:00,  2.50batch/s, loss=1.59]


Fold 4 Epoch 13/20, Loss: 1.724833672559714
New best model saved with loss: 1.724833672559714


Fold 4 Epoch 14/20: 100%|██████████| 316/316 [02:06<00:00,  2.51batch/s, loss=1.35]


Fold 4 Epoch 14/20, Loss: 1.7234142324592494
New best model saved with loss: 1.7234142324592494


Fold 4 Epoch 15/20: 100%|██████████| 316/316 [02:06<00:00,  2.51batch/s, loss=1.64]


Fold 4 Epoch 15/20, Loss: 1.722093550464775
New best model saved with loss: 1.722093550464775


Fold 4 Epoch 16/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.49] 


Fold 4 Epoch 16/20, Loss: 1.7188582352445096
New best model saved with loss: 1.7188582352445096


Fold 4 Epoch 17/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.91]


Fold 4 Epoch 17/20, Loss: 1.7188928259324423


Fold 4 Epoch 18/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.92]


Fold 4 Epoch 18/20, Loss: 1.7187406699868697
New best model saved with loss: 1.7187406699868697


Fold 4 Epoch 19/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.88]


Fold 4 Epoch 19/20, Loss: 1.7185485042348694
New best model saved with loss: 1.7185485042348694


Fold 4 Epoch 20/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.67]


Fold 4 Epoch 20/20, Loss: 1.7182461977759493
New best model saved with loss: 1.7182461977759493


Some weights of Dinov2ForImageClassification were not initialized from the model checkpoint at facebook/dinov2-small and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


cuda
Dinov2ForImageClassification(
  (dinov2): Dinov2Model(
    (embeddings): Dinov2Embeddings(
      (patch_embeddings): Dinov2PatchEmbeddings(
        (projection): Conv2d(3, 384, kernel_size=(14, 14), stride=(14, 14))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): Dinov2Encoder(
      (layer): ModuleList(
        (0-11): 12 x Dinov2Layer(
          (norm1): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
          (attention): Dinov2SdpaAttention(
            (attention): Dinov2SdpaSelfAttention(
              (query): Linear(in_features=384, out_features=384, bias=True)
              (key): Linear(in_features=384, out_features=384, bias=True)
              (value): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): Dinov2SelfOutput(
              (dense): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=F

Fold 5 Epoch 1/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.87]


Fold 5 Epoch 1/20, Loss: 2.3084834802754317
New best model saved with loss: 2.3084834802754317


Fold 5 Epoch 2/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.9] 


Fold 5 Epoch 2/20, Loss: 2.0070327622226523
New best model saved with loss: 2.0070327622226523


Fold 5 Epoch 3/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=2.13]


Fold 5 Epoch 3/20, Loss: 1.9759608141229124
New best model saved with loss: 1.9759608141229124


Fold 5 Epoch 4/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.76]


Fold 5 Epoch 4/20, Loss: 1.933994696864599
New best model saved with loss: 1.933994696864599


Fold 5 Epoch 5/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=2.03]


Fold 5 Epoch 5/20, Loss: 1.9151026018058197
New best model saved with loss: 1.9151026018058197


Fold 5 Epoch 6/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.69]


Fold 5 Epoch 6/20, Loss: 1.8080909172945385
New best model saved with loss: 1.8080909172945385


Fold 5 Epoch 7/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.67]


Fold 5 Epoch 7/20, Loss: 1.785421830943868
New best model saved with loss: 1.785421830943868


Fold 5 Epoch 8/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.91]


Fold 5 Epoch 8/20, Loss: 1.7750940926467316
New best model saved with loss: 1.7750940926467316


Fold 5 Epoch 9/20: 100%|██████████| 316/316 [02:06<00:00,  2.51batch/s, loss=1.83]


Fold 5 Epoch 9/20, Loss: 1.7660945736909215
New best model saved with loss: 1.7660945736909215


Fold 5 Epoch 10/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.5] 


Fold 5 Epoch 10/20, Loss: 1.75874834196477
New best model saved with loss: 1.75874834196477


Fold 5 Epoch 11/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.92]


Fold 5 Epoch 11/20, Loss: 1.7400009168099753
New best model saved with loss: 1.7400009168099753


Fold 5 Epoch 12/20: 100%|██████████| 316/316 [02:04<00:00,  2.53batch/s, loss=1.75]


Fold 5 Epoch 12/20, Loss: 1.7356485626365565
New best model saved with loss: 1.7356485626365565


Fold 5 Epoch 13/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.85]


Fold 5 Epoch 13/20, Loss: 1.733198900388766
New best model saved with loss: 1.733198900388766


Fold 5 Epoch 14/20: 100%|██████████| 316/316 [02:05<00:00,  2.53batch/s, loss=1.83]


Fold 5 Epoch 14/20, Loss: 1.732127771347384
New best model saved with loss: 1.732127771347384


Fold 5 Epoch 15/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.85]


Fold 5 Epoch 15/20, Loss: 1.7305447715747206
New best model saved with loss: 1.7305447715747206


Fold 5 Epoch 16/20: 100%|██████████| 316/316 [02:03<00:00,  2.55batch/s, loss=1.4] 


Fold 5 Epoch 16/20, Loss: 1.7274477991122235
New best model saved with loss: 1.7274477991122235


Fold 5 Epoch 17/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.74]


Fold 5 Epoch 17/20, Loss: 1.7271366772017902
New best model saved with loss: 1.7271366772017902


Fold 5 Epoch 18/20: 100%|██████████| 316/316 [02:05<00:00,  2.52batch/s, loss=1.71]


Fold 5 Epoch 18/20, Loss: 1.7269543352760846
New best model saved with loss: 1.7269543352760846


Fold 5 Epoch 19/20: 100%|██████████| 316/316 [02:04<00:00,  2.54batch/s, loss=1.72]


Fold 5 Epoch 19/20, Loss: 1.726732172166245
New best model saved with loss: 1.726732172166245


Fold 5 Epoch 20/20: 100%|██████████| 316/316 [02:05<00:00,  2.51batch/s, loss=1.73]


Fold 5 Epoch 20/20, Loss: 1.7266244586509993
New best model saved with loss: 1.7266244586509993


Some weights of Dinov2ForImageClassification were not initialized from the model checkpoint at facebook/dinov2-small and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipykernel_1482/3905504083.py:72: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. W

Fold 1 Confusion Matrix:
[[ 51   0   8   0   0   0 105   0   0  65   0   0  41  25   0  12   0   0]
 [ 15   0   4   0   0   0  15   0   0  20   0   0  18  11   0   8   0   0]
 [  5   0  75   0   0   0  20   0   0  12   0   0   9   2   0  11  57   0]
 [  1   0   0   0   0   0   4   0   0   2   0   0   1   0   0   2   0   0]
 [  0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  21   0]
 [ 49   0   9   0   0   0 187   0   0   4   0   0  17   2   0   2   1   0]
 [  0   0   0   0   0   0   1   0   2   0   0   0   0   0   0   0  73   0]
 [  0   0   1   0   0   0   0   0  19   0   0   0   0   0   0   0   2   0]
 [ 32   0   7   0   0   0  11   0   0 100   0   1  30  27   0  16   0   0]
 [  7   0   0   0   0   0   5   0   0   9   0   0   3  13   0   3   0   0]
 [  4   0  25   0   0   0  13   0   0  12   0   0   7   0   0   4   6   0]
 [ 40   0   8   0   0   0  39   0   0  53   0   0  62  11   0  17   0   0]


/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

Fold 2 Confusion Matrix:
[[ 54   0  12   0   0   0  99   0   0  53   0   0  54  17   0  18   0   1]
 [ 13   0   8   0   0   0  15   0   0  26   0   0  15   8   0   7   0   0]
 [  2   0  71   0   0   0  15   0   0  24   0   0  18   0   0   7  54   0]
 [  1   0   0   0   0   0   6   0   0   1   0   0   2   0   0   1   0   0]
 [  0   0   3   0   0   0   0   0   0   0   0   0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0  21   0]
 [ 42   0   7   0   0   0 185   0   0   2   0   0  31   0   0   4   0   0]
 [  0   0   6   0   0   0   0   0   0   0   0   0   0   0   0   0  71   0]
 [  0   0   0   0   0   0   0   0  22   0   0   0   0   0   0   0   2   0]
 [ 15   0   7   0   0   0  13   0   1 123   1   0  40  15   0   9   1   0]
 [  3   0   1   0   0   0   5   0   0  21   0   0   7   1   0   3   0   0]
 [  4   0  21   0   0   0  14   0   0   7   0   0  11   1   0   5   9   0]
 [ 32   0  15   0   0   0  45   0   0  52   0   0  64  13   0   9   0   0]


/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

Fold 3 Confusion Matrix:
[[ 58   0   7   0   0   0 112   0   0  55   0   0  41  20   0  15   0   0]
 [ 18   0   2   0   0   0  21   0   0  26   0   0  14   8   0   2   1   0]
 [  3   0  67   0   0   0  18   0   0  16   0   0  17   3   0  10  57   0]
 [  2   0   1   0   0   0   3   0   0   1   0   0   0   2   0   1   1   0]
 [  0   0   1   0   0   0   0   0   0   0   0   0   1   0   0   0  14   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  21   0]
 [ 49   0   6   0   0   0 180   0   0   4   0   0  27   1   0   4   0   0]
 [  0   0   3   0   0   0   0   0   2   0   0   0   0   0   0   0  71   0]
 [  0   0   1   0   0   0   0   0  20   0   0   0   0   0   0   0   3   0]
 [ 24   0  10   0   0   0  14   0   0 125   0   0  29  15   0   7   1   0]
 [  5   0   1   0   0   0   4   0   0  21   0   0   2   5   0   2   0   0]
 [  3   0  33   0   0   0  11   0   0  11   0   0   7   1   0   1   5   0]
 [ 36   0  14   0   0   0  61   0   0  41   0   0  58   8   0  11   1   0]


/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

Fold 4 Confusion Matrix:
[[ 60   0  11   0   0   0  99   0   0  47   0   0  44  22   0  23   0   1]
 [  9   0   2   0   0   0  16   0   0  25   0   0  24   6   0   9   0   1]
 [  5   0  76   0   0   0  14   0   0  15   0   2   9   4   0   3  63   0]
 [  1   0   1   0   0   0   3   0   0   2   0   0   0   1   0   1   0   1]
 [  0   0   4   0   0   0   0   0   0   0   0   1   0   0   0   0  11   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  21   0]
 [ 29   0   7   0   0   0 200   0   0   6   0   1  23   1   0   4   0   0]
 [  0   0   2   0   0   1   0   0   0   1   0   0   0   0   0   0  71   0]
 [  0   0   1   0   0   1   0   0  19   0   0   0   0   0   0   0   3   0]
 [ 25   0   8   0   0   0  21   0   0  95   0   0  29  31   0  16   0   0]
 [  7   0   1   0   0   0   9   0   0  16   0   0   3   3   0   1   0   0]
 [  2   0  23   0   0   0  13   0   0  11   0   1   8   1   0   4   8   1]
 [ 31   0   6   0   0   0  47   0   0  56   0   3  61  12   0  13   0   1]


/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

Fold 5 Confusion Matrix:
[[ 53   0   9   0   0   0  99   0   0  52   0   0  53  30   0  10   1   0]
 [ 13   0   4   0   0   0  16   0   0  30   0   0  15   9   0   4   0   0]
 [  3   0  72   0   0   0  12   0   1  14   0   0  16   2   0   6  65   0]
 [  0   0   1   0   0   0   5   0   0   2   0   0   1   1   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  16   0]
 [  0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0  20   0]
 [ 31   0   7   0   0   0 191   0   0   1   0   1  31   4   0   4   1   0]
 [  0   0   3   0   0   0   0   0   0   0   0   0   0   0   0   0  73   0]
 [  0   0   0   0   0   0   0   0  20   0   0   0   0   0   0   0   3   0]
 [ 27   0   9   0   0   0  17   0   0 101   0   0  33  25   0  12   0   0]
 [  8   0   1   0   0   0   6   0   0  11   0   0   2  11   0   1   0   0]
 [  2   0  21   0   0   0  14   0   0  14   0   1  11   1   0   0   8   0]
 [ 22   0  12   0   0   0  56   0   0  54   0   1  52  22   0  11   0   0]


/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

In [9]:
print(fold_results)

{1: ({'AmorfHead': {'precision': 0.16943521594684385, 'recall': 0.16612377850162866, 'f1-score': 0.16776315789473684, 'support': 307.0}, 'AsymmetricNeck': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 91.0}, 'CurlyTail': {'precision': 0.3787878787878788, 'recall': 0.39267015706806285, 'f1-score': 0.3856041131105398, 'support': 191.0}, 'DoubleHead': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 10.0}, 'DoubleTail': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 16.0}, 'LongTail': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 21.0}, 'NarrowAcrosome': {'precision': 0.3953488372093023, 'recall': 0.6900369003690037, 'f1-score': 0.5026881720430108, 'support': 271.0}, 'Normal': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 76.0}, 'PinHead': {'precision': 0.8636363636363636, 'recall': 0.8636363636363636, 'f1-score': 0.8636363636363636, 'support': 22.0}, 'PyriformHead': {'precision': 0.2358490566037736, 'recall': 0.4

In [10]:
with open(os.path.join(data_dir, 'convnextv2tiny_report.txt'), 'w') as f:
    print(fold_results, file=f)

In [11]:
def save_confusion_matrix(cm, classes, output_path, fontsize=11):
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap="OrRd", cbar=True, 
                xticklabels=classes, yticklabels=classes, annot_kws={"size": fontsize})
    
    plt.xlabel("Predicted", fontsize=fontsize)
    plt.ylabel("Actual", fontsize=fontsize)
    plt.title("Confusion Matrix", fontsize=fontsize)
    plt.xticks(rotation=90, fontsize=fontsize)
    plt.yticks(rotation=0, fontsize=fontsize)
    
    plt.tight_layout() 
    plt.savefig(output_path)
    plt.close()
    print(f"Confusion matrix saved to {output_path}")

classes = datasets.ImageFolder(root=os.path.join(data_dir, 'fold1', 'test'), transform=transform).classes
for i in range(1, 6):
    save_confusion_matrix(fold_results[i][1], classes, os.path.join(data_dir, f'convnextv2tiny_fold{i}.png'))

Confusion matrix saved to datasets/Boya3/convnextv2tiny_fold1.png
Confusion matrix saved to datasets/Boya3/convnextv2tiny_fold2.png
Confusion matrix saved to datasets/Boya3/convnextv2tiny_fold3.png
Confusion matrix saved to datasets/Boya3/convnextv2tiny_fold4.png
Confusion matrix saved to datasets/Boya3/convnextv2tiny_fold5.png


In [12]:
def matrix_sum(fold_results):
    cumulative_cm = None


    for fold_idx, (report, cm) in fold_results.items():
        # Combine confusion matrices
        if cumulative_cm is None:
            cumulative_cm = cm
        else:
            cumulative_cm += cm

    return cumulative_cm

cumulative_cm = matrix_sum(fold_results)

print("Cumulative Confusion Matrix:")
print(cumulative_cm)
with open(os.path.join(data_dir, 'cumulative_cm.txt'), 'w') as f:
    print(cumulative_cm, file=f)
save_confusion_matrix(cumulative_cm, classes, os.path.join(data_dir, 'cumulative_cm.png'))

Cumulative Confusion Matrix:
[[ 276    0   47    0    0    0  514    0    0  272    0    0  233  114
     0   78    1    2]
 [  68    0   20    0    0    0   83    0    0  127    0    0   86   42
     0   30    1    1]
 [  18    0  361    0    0    0   79    0    1   81    0    2   69   11
     0   37  296    0]
 [   5    0    3    0    0    0   21    0    0    8    0    0    4    4
     0    5    1    1]
 [   0    0   10    0    0    0    0    0    0    0    0    1    1    0
     0    0   69    0]
 [   0    0    0    0    0    0    0    0    2    0    0    0    0    0
     0    0  104    0]
 [ 200    0   36    0    0    0  943    0    0   17    0    2  129    8
     0   18    2    0]
 [   0    0   14    0    0    1    1    0    4    1    0    0    0    0
     0    0  359    0]
 [   0    0    3    0    0    1    0    0  100    0    0    0    0    0
     0    0   13    0]
 [ 123    0   41    0    0    0   76    0    1  544    1    1  161  113
     0   60    2    0]
 [  30    0    4    0

In [13]:
def classification_report_from_confusion_matrix(confusion_matrix, class_names):
    y_true = np.zeros(np.sum(confusion_matrix), dtype=int)
    y_pred = np.copy(y_true)

    i = 0
    for target in range(len(confusion_matrix)):
        for pred in range(len(confusion_matrix)):
            n = confusion_matrix[target][pred]
            y_true[i:i+n] = target
            y_pred[i:i+n] = pred
            i += n

    return classification_report(y_true, y_pred, digits=4, target_names=class_names)

avg_report = classification_report_from_confusion_matrix(cumulative_cm, classes)
print (avg_report)
with open(os.path.join(data_dir, 'average_report.txt'), 'w') as f:
    print(avg_report, file=f)

                precision    recall  f1-score   support

     AmorfHead     0.2125    0.1796    0.1946      1537
AsymmetricNeck     0.0000    0.0000    0.0000       458
     CurlyTail     0.3546    0.3780    0.3659       955
    DoubleHead     0.0000    0.0000    0.0000        52
    DoubleTail     0.0000    0.0000    0.0000        81
      LongTail     0.0000    0.0000    0.0000       106
NarrowAcrosome     0.4020    0.6959    0.5096      1355
        Normal     0.0000    0.0000    0.0000       380
       PinHead     0.8333    0.8547    0.8439       117
  PyriformHead     0.2348    0.4844    0.3163      1123
     RoundHead     0.0000    0.0000    0.0000       201
     ShortTail     0.1250    0.0056    0.0107       359
   TaperedHead     0.2126    0.2583    0.2332      1150
     ThickNeck     0.2175    0.1520    0.1790       934
      ThinNeck     0.0000    0.0000    0.0000       180
   TwistedNeck     0.2273    0.1404    0.1735       855
   TwistedTail     0.6930    0.8893    0.7790  

/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/gurol/anaconda3/envs/araproje/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita